In [36]:
import numpy as np
def hilbert(n):
    A = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            A[i,j] = 1/(i+j+1) #debido a la correccion de rangos sumamos 1 a i y 1 a j entonces obtenemos i+j+1
    return A

In [37]:
print(hilbert(100))

[[1.         0.5        0.33333333 ... 0.01020408 0.01010101 0.01      ]
 [0.5        0.33333333 0.25       ... 0.01010101 0.01       0.00990099]
 [0.33333333 0.25       0.2        ... 0.01       0.00990099 0.00980392]
 ...
 [0.01020408 0.01010101 0.01       ... 0.00512821 0.00510204 0.00507614]
 [0.01010101 0.01       0.00990099 ... 0.00510204 0.00507614 0.00505051]
 [0.01       0.00990099 0.00980392 ... 0.00507614 0.00505051 0.00502513]]


In [ ]:
def Gauss_Seidel(A, b, x_0, tol=1e-10):
    x = x_0.astype(float).copy()
    k = 0
    norm_x = []
    norm_r = []
    while np.linalg.norm(b - A @ x) > tol and k < 500: #criterio de residuos y de cantidad maxima de iteraciones   
        for i in range(len(A)):
            s1 = 0
            s2 = 0
            for j in range(0, i):
                s1 += A[i, j] * x[j]  
            for j in range(i + 1, len(A)):
                s2 += A[i, j] * x[j] 
            x[i] = (b[i] - s1 - s2) / A[i, i]
        k += 1
        norm_x.append(np.linalg.norm(x))
        norm_r.append(np.linalg.norm(b - A@x))
        #print(f"Iteration {k}: x = {x}, Residual = {np.linalg.norm(b - A @ x)}")
    return x, norm_x, norm_r

In [47]:
A = hilbert(100)
b = np.ones(100)
x0 = np.zeros_like(b)
x, norm_x, norm_r = Gauss_Seidel(A,b,x0,1e-10)